server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.25.71
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  thymeleaf:
    destPath: C:\Users\71042\Desktop\nginx-1.14.0\html\item